package com.servicehub.crm.mapper;

import com.servicehub.crm.lead.dto.ServiceRequestResponse;
import com.servicehub.crm.lead.dto.ServiceRequestSaveRequest;
import com.servicehub.crm.lead.entity.ServiceRequest;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

@Mapper(componentModel = "spring")
public interface ServiceRequestMapper {

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "customerId", ignore = true)     // set by the service from the authenticated principal
    @Mapping(target = "subCategory", ignore = true)     // relations — resolved by the service, not the mapper
    @Mapping(target = "address", ignore = true)
    @Mapping(target = "assignedVendor", ignore = true)
    @Mapping(target = "requestCode", ignore = true)     // generated by the service on create
    ServiceRequest toEntity(ServiceRequestSaveRequest request);

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "customerId", ignore = true)
    @Mapping(target = "subCategory", ignore = true)
    @Mapping(target = "address", ignore = true)
    @Mapping(target = "assignedVendor", ignore = true)
    @Mapping(target = "requestCode", ignore = true)
    void updateEntityFromRequest(ServiceRequestSaveRequest request, @MappingTarget ServiceRequest serviceRequest);

    @Mapping(target = "vendorId", source = "assignedVendor.id")
    @Mapping(target = "vendorName", source = "assignedVendor.businessName")
    @Mapping(target = "subCategoryId", source = "subCategory.id")
    @Mapping(target = "subCategoryName", source = "subCategory.name")
    @Mapping(target = "addressId", source = "address.id")
    ServiceRequestResponse toResponse(ServiceRequest serviceRequest);
}
